name: STM32CubeIDE Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Cubectl
      run: |
        wget https://github.com/kshypachov/stm32_builder/raw/refs/heads/main/st-stm32cubeclt_1.16.0_21983_20240628_1741_amd64.sh

    - name: Install Cubectl
      run: |
        export LICENSE_ALREADY_ACCEPTED=1
        chmod +x st-stm32cubeclt_1.16.0_21983_20240628_1741_amd64.sh
        yes "" | ./st-stm32cubeclt_1.16.0_21983_20240628_1741_amd64.sh
        export PATH="$PATH:/home/runner/st/stm32cubeclt_1.16.0/Ninja/bin"
        export PATH="$PATH:/home/runner/st/stm32cubeclt_1.16.0/CMake/bin"
        export PATH="$PATH:/home/runner/st/stm32cubeclt_1.16.0/GNU-tools-for-STM32/bin"

    - name: Install make
      run: |
        sudo apt update
        sudo apt install make 

    - name: Clear Build folder
      run: |
        make clean -C ./Debug
        
    - name: Build project with Makefile
      run: |
        make all -C ./Debug
